trabalhonatalcare/natalcare/natalcare/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nc.urls')),
]

trabalhonatalcare/natalcare/nc/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

urlpatterns = [
    path('cadastro/', cadastrousuario.as_view(), name='cadastro'),
    path('procadu/', cadastrousuario.as_view(), name='procadu'),
    path('procadc/', cadastroclinica.as_view(), name='procadc'),
    path('login/', logusuario.as_view(), name='log'),
    path('prologu/', logusuario.as_view(), name='prologu'),
    path('prologc/', logclinica.as_view(), name='prologc'),
    path('', menu.as_view(), name='menu'),
    path('perfil/', perfil.as_view(), name="perfil"),
    path('properfil/', perfil.as_view(), name="properfil"),
    path('pesq/', resultados.as_view(), name="pesq"),
    path('logoutu/', logoutu.as_view(), name="logoutu"),
    path('msc/', mudar_senha_clin.as_view(), name="msc"),
    path('promsc/', mudar_senha_clin.as_view(), name="promsc"),
    path('clind/', clin_dados.as_view(), name="clinc"),
    path('clind/<int:id>/', clinusu.as_view(), name="clinu"),
    path('clined/', clinedit.as_view(), name="clined"),
    path('proclined/', clinedit.as_view(), name="proclined"),
    path('coment/<int:id>/', comentario.as_view(), name="coment"),
    path('favs/<int:id>/', favoritos.as_view(), name="favs"),
    path('chatusu/<int:id>/', chatusu.as_view(), name="chatusu"),
    path('chatclin/', chatclin.as_view(), name="chatclin"),
    path('prochatclin/<int:id>', prochatclin.as_view(), name="prochatclin"),
]

trabalhonatalcare/natalcare/nc/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class especialidades(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class plano(models.Model):
    nome = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='planos', blank=True)

    def __str__(self):
        return self.nome

class endereco(models.Model):
    logradouro = models.CharField(max_length=100)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=8)
    complemento = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.logradouro}, {self.numero}, {self.complemento + ','  if self.complemento  else ''} {self.bairro} - {self.cep}, {self.cidade}/{self.estado}"

class clinica(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=14, unique=True)
    telefone = models.CharField(max_length=11)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=10, unique=True)
    endereco = models.OneToOneField(endereco, on_delete=models.CASCADE)
    plano = models.ManyToManyField(plano, blank=True)
    especialidades = models.ManyToManyField(especialidades, blank=True)
    foto = models.ImageField(blank=True, null=True, default="/batman-resolve-in-the-rain.jpg", upload_to="media")
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.nome
    
class usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=11, unique=True)
    email = models.EmailField(unique=True)
    senha = models.CharField(max_length=10, unique=True)
    telefone = models.CharField(max_length=11)
    endereco = models.OneToOneField(endereco, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class historico(models.Model):
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['data']
        unique_together = ['usuario', 'clinica']

    def __str__(self):
        return f"{self.usuario.nome} -> {self.clinica.nome}"

class favorito(models.Model):
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['data']
        unique_together = ['usuario', 'clinica']

    def __str__(self):
        return f"{self.usuario.nome} -> {self.clinica.nome}"
    
class comentarios(models.Model):
    comentario = models.TextField()
    avaliacao = models.BooleanField()
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)

    def __str__(self):
        return self.comentario

class chat(models.Model):
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    clinica = models.ForeignKey(clinica, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.usuario.nome} -> {self.clinica.nome}"

class mensagens(models.Model):
    mensagem = models.TextField()
    data = models.DateTimeField(auto_now_add=True)
    chat = models.ForeignKey(chat, on_delete=models.CASCADE)
    remetente = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['data']

    def __str__(self):
        return self.mensagem

trabalhonatalcare/natalcare/nc/views.py
from django.shortcuts import *
from django.views import View
from django.contrib import messages
from .models import *
from django.contrib.auth import authenticate, login, logout
from .models import usuario
from django.contrib.auth.models import User

# Create your views here.
class cadastrousuario(View):
    def get(self, request):
        return render(request, 'site/cadastro/cad.html')
    
    def post(self, request):
        nome = request.POST.get('nome')
        cpf = request.POST.get('cpf')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        telefone = request.POST.get('telefone')
        logradouro = request.POST.get('logradouro')
        numero = request.POST.get('numero')
        bairro = request.POST.get('bairro')
        cidade = request.POST.get('cidade')
        estado = request.POST.get('estado')
        cep = request.POST.get('cep')
        complemento = request.POST.get('complemento')
        
        
        try:
            clin = clinica.objects.get(email=email, senha=senha)
            if clin:
                messages.error(request, 'Usuário já cadastrado como clínica')
                return render(request, 'site/cadastro/cad.html')
        except:
            try:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Email já está cadastrado.')
                    return render(request, 'site/cadastro/cad.html')
                else:
                    user = User.objects.create_user(
                    username=nome,
                    email=email,
                    first_name=nome,
                    password=senha
                    )
                    user.save()

                end = endereco.objects.create(logradouro=logradouro, numero=numero, bairro=bairro, cidade=cidade, estado=estado, cep=cep, complemento=complemento)
                usu = usuario.objects.create(nome=nome, email=email, senha=senha, telefone=telefone, endereco=end, user=user, cpf=cpf)
                messages.success(request, 'Usuário cadastrado com sucesso')
                user = authenticate(request, username=usu.nome, password=senha)
                login(request, user)
                return render(request, 'site/menu/menu.html')
            except Exception as e:
                messages.error(request, 'Erro ao cadastrar usuário')
                return render(request, 'site/cadastro/cad.html')
            
class logusuario(View):
    def get(self, request):
        return render(request, 'site/login/log.html')
    
    def post(self, request):
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        
        try:
            usu = usuario.objects.get(email=email, senha=senha)
            user = authenticate(request, username=usu.nome, password=senha)
            if user:
                login(request, user)
        except:
            messages.error(request, 'Usuário não encontrado')
            return render(request, 'site/login/log.html')
        return redirect('menu')

class cadastroclinica(View):
    def get(self, request):
        return render(request, 'site/cadastro/cad.html')
    
    def post(self, request):
        nome = request.POST.get('nome')
        cnpj = request.POST.get('cnpj')
        telefone = request.POST.get('telefone')
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        logradouro = request.POST.get('logradouro')
        numero = request.POST.get('numero')
        bairro = request.POST.get('bairro')
        cidade = request.POST.get('cidade')
        estado = request.POST.get('estado')
        cep = request.POST.get('cep')
        complemento = request.POST.get('complemento')

        try:
            user = usuario.objects.get(email=email, senha=senha)
            if user:
                messages.error(request, 'Clínica já cadastrado como usuário')
            return render(request, 'site/cadastro/cad.html')
        except:
            try:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'Email já está cadastrado.')
                    return render(request, 'site/cadastro/cad.html')
                else:
                    user = User.objects.create_user(
                    username=nome,
                    email=email,
                    first_name=nome,
                    password=senha
                    )
                    user.save()

                end = endereco.objects.create(logradouro=logradouro, numero=numero, bairro=bairro, cidade=cidade, estado=estado, cep=cep, complemento=complemento)
                clin = clinica.objects.create(nome=nome, cnpj=cnpj, telefone=telefone, email=email, senha=senha, endereco=end, user=user)
                messages.success(request, 'Clínica cadastrado com sucesso')
                user = authenticate(request, username=clin.nome, password=senha)
                login(request, user)
                return redirect('clined')
            except Exception as e:
                messages.error(request, 'Erro ao cadastrar clínica')
                return render(request, 'site/cadastro/cad.html')
           
    
class logclinica(View):
    def get(self, request):
        return render(request, 'site/login/log.html')
    
    def post(self, request):
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        
        try:
            usu = clinica.objects.get(email=email, senha=senha)
            user = authenticate(request, username=usu.nome, password=senha)
            if user:
                login(request, user)
        except:
            messages.error(request, 'Clínica não encontrada')
            return render(request, 'site/login/log.html')
        return redirect('clinc')

class logoutu(View):
    def get(self, request):
        logout(request)
        return render(request, 'site/login/log.html')

class menu(View):
    def get(self, request):
        if request.user.is_authenticated:
            hist = historico.objects.filter(usuario=request.user.usuario)
            return render(request, 'site/menu/menu.html', {"hist_usu": hist})
        else:
            return render(request, 'site/menu/menu.html')
    
    def post(self, request):
        try:
            clin = clinica.objects.get(nome=request.POST.get('pesqi'))
            if clin == clinica.objects.get(nome=clin.nome):
                hist = historico.objects.filter(usuario=request.user.usuario)
                if hist.count() == 3:
                    hist.first().delete()
                historico.objects.create(clinica=clin, usuario=request.user.usuario)
                hist = historico.objects.filter(usuario=request.user.usuario)
                return render(request, 'site/menu/menu.html', {"clinica": clin, "hist_usu": hist})
        except Exception as e:
            messages.error(request, f'Clínica não encontrada{e}')
            return render(request, 'site/menu/menu.html')
        

class mudar_senha_clin(View):
    def get(self, request):
        return render(request, 'site/senha/sen.html')
    
    def post(self, request):
        try:
            clin = clinica.objects.get(email=request.POST.get('email'))
            if request.POST.get('nsenha') == request.POST.get('csenha'):
                # breakpoint()
                clin.senha = request.POST.get('csenha')
                clin.save()
                return render(request, 'site/login/log.html')
            else:
                messages.error(request, 'As senhas tem que ser iguais')
                return render(request, 'site/senha/sen.html')
        except:
            messages.error(request, 'Clínica não encontrada')
            return render(request, 'site/senha/sen.html')

class perfil(View):
    def get(self, request):
        fav = favorito.objects.filter(usuario=request.user.usuario)
        return render(request, 'site/perfil/perfil.html', {"favo": fav})
    
    def post(self, request):
        try:
            usu = request.user.usuario
            nome = request.POST.get('nome')
            telefone = request.POST.get('telefone')
            cpf = request.POST.get('cpf')
            email = request.POST.get('email')
            logradouro = request.POST.get('logradouro')
            numero = request.POST.get('numero')
            complemento = request.POST.get('complemento')
            cep = request.POST.get('cep')
            bairro = request.POST.get('bairro')
            cidade = request.POST.get('cidade')
            estado = request.POST.get('estado')
            usu.nome = nome
            usu.telefone = telefone
            usu.cpf = cpf
            usu.email = email
            usu.endereco.logradouro = logradouro
            usu.endereco.numero = numero
            usu.endereco.complemento = complemento
            usu.endereco.cep = cep
            usu.endereco.bairro = bairro
            usu.endereco.cidade = cidade
            usu.endereco.estado = estado
            usu.endereco.save()
            usu.save()
            messages.success(request, "Dados atualizados!")
            return render(request, 'site/perfil/perfil.html')
        except:
            messages.error(request, "deu bo familia")
            return render(request, 'site/perfil/perfil.html')

class resultados(View):
    def get(self, request):
        return render(request, 'site/pesquisa/pesq.html', {"esp": especialidades.objects.all(), "plan": plano.objects.all()})
    
    def post(self, request):
        i = request.POST.get("pesqi")
        p = request.POST.get("plan")
        e = request.POST.get("esp")
        # respe = clinica.objects.filter(plano=p, especialidades=e)

trabalhonatalcare/natalcare/nc/templates/site/chat/chatclin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clínica</title>
    <link rel="stylesheet" href="{% static 'chatclin_est.css' %}">
</head>

<body>
    <header class="header">
        <div class="logo">natal<span>care</span></div>
        <a href="{% url 'pesq' %}"><input type="text" placeholder="Clínica XYZ..." class="search-input"></a>
        <span id="prfl-login">
            <img src="{% static 'imagens_site/perfil.svg' %}" alt="user">
            {% if request.user.clinica %}
                <button class="login-button" id="usu" onclick="menuh()">{{request.user.clinica}}</button>
                <section id="menuh">
                    <ul>
                        <li><a href="{% url 'clined' %}">Perfil</a></li>
                        <li><a href="{% url 'chatclin' %}">Agendamento</a></li>
                        <li><a href="{% url 'logoutu' %}">Sair</a></li>
                    </ul>
                </section>
            {% endif %}
        </span>
    </header>

    <main>
        <section id="conversas">
            <h1>Conversas</h1>

            {% for i in conv_iniciada %}
                <a href="{% url 'prochatclin' i.usuario.id %}" id="convs">
                    <section id="clinicas">
                        <img src="{% static 'imagens_site/clingen.svg' %}" alt="">
                        <h2>{{i.usuario.nome}}</h2>
                    </section>
                </a>
            {% endfor %}

        </section>

        <section id="chat">
            {% if conversa %}
                <section id="nome-clin">
                    <h1>{{conversa.usuario.nome}}</h1>
                </section>

                <section id="area-chat">
                    {% for i in conversa.mensagens_set.all %}
                        {% if i.remetente.username == request.user.clinica.nome %}
                            <section id="clinmen"><p id="clinmens">{{i.mensagem}}</p></section>
                        {% else %}
                            <section id="usumen"><p id="usumens">{{i.mensagem}}</p></section>
                        {% endif %}
                    {% endfor %}
                </section>

                <form id="digitex" action="{% url 'prochatclin' conversa.usuario.id %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="mens" id="">
                    <input type="submit" name="" id="">
                </form>
            {% endif %}
        </section>
    </main>

    <footer class="footer">
        <div class="footer-menu">
            <ul>
                <li><strong>Início</strong><br>Home<br>Login<br>Cadastro</li>
                <li><strong>Sobre nós</strong><br>Informações<br>Contato</li>
                <li><strong>Suporte</strong><br>FAQ<br>Chat</li>
            </ul>
        </div>
        <div class="footer-logo">
            <p class="brand-name">natalcare</p>
            <p class="brand-slogan">Sua pesquisa acaba aqui!</p>
        </div>
        <div class="footer-social">
            <!-- LinkedIn SVG -->
            <a href="#" title="LinkedIn">
                <img src="{% static 'imagens_site/linkedin.svg' %}" alt="">
            </a>
            <!-- Instagram SVG -->
            <a href="#" title="Instagram">
                <img src="{% static 'imagens_site/instagram.svg' %}" alt="">
            </a>
            <!-- Facebook SVG -->
            <a href="#" title="Facebook">
                <img src="{% static 'imagens_site/facebook.svg' %}" alt="">
            </a>
            <!-- Twitter SVG -->
            <a href="#" title="Twitter">
                <img src="{% static 'imagens_site/x.svg' %}" alt="">
            </a>
        </div>
    </footer>


    <script>
        var inputs = document.querySelectorAll('input')
        var select = document.getElementById('estado')
        var edit = document.getElementById("edit")
        var btn = document.getElementById("btns")
        var menu = document.getElementById('menuh')
        var usu = document.getElementById('usu')

        function editar(){
            inputs.forEach(input => {
            input.disabled = false;
            input.style.border = "1px solid black";
            select.disabled = false;
            select.style.border = "1px solid black";
        })}

        function menuh(){
            menu.style.display = 'flex';
        }
    </script>
</body>
</html>

trabalhonatalcare/natalcare/nc/templates/site/chat/chatusu.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clínica</title>
    <link rel="stylesheet" href="{% static 'chatusu_est.css' %}">
</head>

<body>
    <header class="header">
        <div class="logo">natal<span>care</span></div>
        <a href="{% url 'pesq' %}"><input type="text" placeholder="Clínica XYZ..." class="search-input"></a>
        <span id="prfl-login">
            <img src="{% static 'imagens_site/perfil.svg' %}" alt="user">
            {% if request.user.usuario %}
                <button class="login-button" id="usu" onclick="menuh()">{{request.user.usuario}}</button>
                <section id="menuh">
                    <ul>
                        <li><a href="{% url 'menu' %}">Menu</a></li>
                        <li><a href="{% url 'perfil' %}">Perfil</a></li>
                        <li>Pesquisa</li>
                        <!-- <li>Agendamento</li> -->
                        <li><a href="{% url 'logoutu' %}">Sair</a></li>
                    </ul>
                </section>
            {% else %}
                <button class="login-button"><a href="{% url 'log' %}" id="no_usu">Entrar</a></button>
            {% endif %}
        </span>
    </header>

    <main>
        <section id="conversas">
            <h1>Conversas</h1>

            {% for i in conv_iniciada %}
                <a href="{% url 'chatusu' i.clinica.id %}" id="convs">
                    <section id="clinicas">
                        <img src="{% static 'imagens_site/clingen.svg' %}" alt="">
                        <h2>{{i.clinica.nome}}</h2>
                    </section>
                </a>
            {% endfor %}

        </section>

        <section id="chat">
            {% if conversa %}
                <section id="nome-clin">
                    <h1>{{conversa.clinica.nome}}</h1>
                </section>

                <section id="area-chat">
                    {% for i in conversa.mensagens_set.all %}
                        {% if i.remetente.username == request.user.usuario.nome %}
                            <section id="clinmen"><p id="clinmens">{{i.mensagem}}</p></section>
                        {% else %}
                            <section id="usumen"><p id="usumens">{{i.mensagem}}</p></section>
                        {% endif %}
                    {% endfor %}
                </section>

                <form id="digitex" action="{% url 'chatusu' conversa.clinica.id  %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="mens" id="">
                    <input type="submit" name="" id="">
                </form>
            {% endif %}
        </section>
    </main>

    <footer class="footer">
        <div class="footer-menu">
            <ul>
                <li><strong>Início</strong><br>Home<br>Login<br>Cadastro</li>
                <li><strong>Sobre nós</strong><br>Informações<br>Contato</li>
                <li><strong>Suporte</strong><br>FAQ<br>Chat</li>
            </ul>
        </div>
        <div class="footer-logo">
            <p class="brand-name">natalcare</p>
            <p class="brand-slogan">Sua pesquisa acaba aqui!</p>
        </div>
        <div class="footer-social">
            <!-- LinkedIn SVG -->
            <a href="#" title="LinkedIn">
                <img src="{% static 'imagens_site/linkedin.svg' %}" alt="">
            </a>
            <!-- Instagram SVG -->
            <a href="#" title="Instagram">
                <img src="{% static 'imagens_site/instagram.svg' %}" alt="">
            </a>
            <!-- Facebook SVG -->
            <a href="#" title="Facebook">
                <img src="{% static 'imagens_site/facebook.svg' %}" alt="">
            </a>
            <!-- Twitter SVG -->
            <a href="#" title="Twitter">
                <img src="{% static 'imagens_site/x.svg' %}" alt="">
            </a>
        </div>
    </footer>


    <script>
        var inputs = document.querySelectorAll('input')
        var select = document.getElementById('estado')
        var edit = document.getElementById("edit")
        var btn = document.getElementById("btns")
        var menu = document.getElementById('menuh')
        var usu = document.getElementById('usu')

        function editar(){
            inputs.forEach(input => {
            input.disabled = false;
            input.style.border = "1px solid black";
            select.disabled = false;
            select.style.border = "1px solid black";
        })}

        function menuh(){
            menu.style.display = 'flex';
        }
    </script>
</body>
</html>